"""added due date and return date to rentals model

Revision ID: 9dc7201f8502
Revises: 7dcdfb3cd648
Create Date: 2021-11-11 16:31:45.534386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc7201f8502'
down_revision = '7dcdfb3cd648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.add_column('rental', sa.Column('return_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'return_date')
    op.drop_column('rental', 'due_date')
    # ### end Alembic commands ###
