"""added rental_id primary key to rentals model

Revision ID: be5605966423
Revises: 9dc7201f8502
Create Date: 2021-11-11 16:35:06.534991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5605966423'
down_revision = '9dc7201f8502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('rental_id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'rental_id')
    # ### end Alembic commands ###
